import random

# r  c  l
SUBJECTS = [
  [1, 0, 7], # HISTORY
  [2, 2, 4], # PAST
  [3, 1, 7], # PRESENT 
  [4, 1, 6], # FUTURE
];

IS = [5, 3, 2];

PREDS = [
  [6, 0, 7], # HISTORY
  [7, 2, 4], # PAST
  [8, 1, 7], # PRESENT 
  [9, 1, 6], # FUTURE
];

words = SUBJECTS + [IS] + PREDS

num_words = len(words) * 2;

header = '''#ifndef HISTORY_IS_PRESENT_H
#define HISTORY_IS_PRESENT_H
/*
 * ClockTHREEjr faceplate file.
 * Autogenerated
 * 
 *      Author: Justin Shaw
 *     Licence: CCC, by
 *    
 * 
 */'''
footer = '''// Minutes hack constants
static uint32_t history_is_present_minute_leds[] = {
  // n_minute_state, n_minute_led,        led0, led2,           led3,           led4...
                  0,            0, 
};
static uint32_t history_is_present_minutes_hack[] = {
};
static Faceplate history_is_present(history_is_present_words, 
                                    history_is_present_displays, 
                                    history_is_present_minute_leds, 
                                    history_is_present_minutes_hack, 
                                    "History_Is_Present");
#endif
'''

print(header)
print('static uint8_t history_is_present_words[] = {')
print(f'    {num_words},')
for word in words:
    r, c, l = word
    print('    ', end='')
    for i in range(2):
        print(f'{2 * c},{2 * r + i},{2 * l}', end=', ' )
    print()
print("};")


print('''static uint8_t history_is_present_displays[] = {
   3, // number of bytes per state''')
last = -1
for i in range(1440//5):
    subj = random.choice(range(4))
    pred = random.choice(range(5, 9))
    while subj + 10 * pred == last:
           subj = random.choice(range(4))
           pred = random.choice(range(5, 9))
    last = subj + 10 * pred
    sentence = ['0'] * 24
    sentence[8] = '1' ## is
    sentence[9] = '1' ## is
    sentence[subj * 2] = '1'
    sentence[subj * 2 + 1] = '1'
    sentence[pred * 2] = '1'
    sentence[pred * 2 + 1] = '1'
    print("    ", end='')
    for i in range(3):
        print('    0b' + ''.join(sentence[i*8:(i+1)*8][::-1]) + ',', end='')
    print()
print('};')

print()
print(footer)    

